version: '3'

services:
  neo4j:
    image: neo4j:3.5
    env_file: .env
    expose:
      - 7474
      - 7687
    # optionnally expose http and bolt on the host:
    # ports:
    #   - '7474:7474'
    #   - '7687:7687'
    volumes:
      - ./neo4j-data:/data
      - ./neo4j-logs:/logs
    restart: unless-stopped

  pythonflask:
    depends_on:
      - neo4j
    build: ./src
    env_file: .env
    expose:
      - 80
    ports:
      - '5000:80'
    volumes:
      - ./src:/app
    restart: unless-stopped

  crontab:
    build: ./crontab
    env_file: .env
    depends_on:
      - pythonflask
    restart: unless-stopped